### ISSUE TITLE
Error using Painting Placer: 

### ISSUE THREAD

**Issue by superp00t** [VcSaJen/YourCustomPaintings#3]
I am running SpongeForge 1.12.2-2555-7.1.0-BETA

```
[Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=yourcustompaintings, name=YourCustomPaintings, version=1.0.0.10, description=Upload your own custom paintings to minecraft server!, source=/home/jjj/sserv/mods/yourcustompaintings-1.0.0.10.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/entity/spawn/EntitySpawnCause
	at com.vcsajen.yourcustompaintings.PaintingPlacer.placePaintingIfPossible(PaintingPlacer.java:177) ~[PaintingPlacer.class:?]
	at com.vcsajen.yourcustompaintings.PaintingPlacer.onInteractBlockEvent(PaintingPlacer.java:221) ~[PaintingPlacer.class:?]
	at org.spongepowered.common.event.listener.MainHandListener_PaintingPlacer_onInteractBlockEvent10.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:315) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:634) [SpongeCommonEventFactory.class:1.12.2-2555-7.1.0-BETA-2833]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:613) [SpongeCommonEventFactory.class:1.12.2-2555-7.1.0-BETA-2833]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1184) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zif000(NetHandlerPlayServer.java:2376) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2555-7.1.0-BETA-2833]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkl000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.1.0-BETA-2833]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zja000(MinecraftServer.java:4007) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by VcSaJen** [comment]
Fixed in ad9bff5.
